name: AWS DEPLOY TO STAGING

#turn off deploy to AWS
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    #For google auth
    steps:
      - name: Check Secret Value
        run: echo "The value of SERVER_SSH_KEY is ${{ secrets.SERVER_SSH_KEY }}"

      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "ec2-18-191-123-27.us-east-2.compute.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/storytime-frontend"
